## USB port
port: /dev/imu


##### Calibration ####
### accelerometer
accel_x_min: -226.93
accel_x_max: 259.64
accel_y_min: -284.30
accel_y_max: 266.85
accel_z_min: -328.86
accel_z_max: 272.80

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [88.0868, 465.674, -242.067]
magn_ellipsoid_transform: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]

# AHRS to robot calibration
imu_yaw_calibration: -90.0

### gyroscope
gyro_average_offset_x: 0.0
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0
